export const backgroundTypeColor: Record<string, string> = {
  bug: 'bg-type-bug',
  dark: 'bg-type-dark',
  dragon: 'bg-type-dragon',
  electric: 'bg-type-electric',
  fairy: 'bg-type-fairy',
  fighting: 'bg-type-fighting',
  fire: 'bg-type-fire',
  flying: 'bg-type-flying',
  ghost: 'bg-type-ghost',
  normal: 'bg-type-normal',
  grass: 'bg-type-grass',
  ground: 'bg-type-ground',
  ice: 'bg-type-ice',
  poison: 'bg-type-poison',
  psychic: 'bg-type-psychic',
  rock: 'bg-type-rock',
  steel: 'bg-type-steel',
  water: 'bg-type-water',
} as const

export const textTypeColor: Record<string, string> = {
  bug: 'text-type-bug',
  dark: 'text-type-dark',
  dragon: 'text-type-dragon',
  electric: 'text-type-electric',
  fairy: 'text-type-fairy',
  fighting: 'text-type-fighting',
  fire: 'text-type-fire',
  flying: 'text-type-flying',
  ghost: 'text-type-ghost',
  normal: 'text-type-normal',
  grass: 'text-type-grass',
  ground: 'text-type-ground',
  ice: 'text-type-ice',
  poison: 'text-type-poison',
  psychic: 'text-type-psychic',
  rock: 'text-type-rock',
  steel: 'text-type-steel',
  water: 'text-type-water',
} as const
